version: "3.8"

services:
  web:
    build: .
    ports:
      - "3001:3001"
    volumes:
      - .:/usr/src/app
    command: npm start
    env_file:
      - .env
    environment:
      - NODE_ENV=production
